# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$script = <<ENDSCRIPT
  sudo yum install -y epel-release
  sudo yum -y update
  sudo yum install -y net-tools
  sudo yum install -y wget
  sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

  sudo yum install -y jenkins
  sudo yum install -y java-1.8.0-openjdk.x86_64
  sudo systemctl start jenkins.service
  sudo systemctl enable jenkins.service
ENDSCRIPT
# Get the default network device name - use printf instead of print to avoid newline in awk
$default_network_router = `ip route | grep -E "^default" | awk '{printf "%s", $5; exit 0}'`



Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  #config.vm.network "forwarded_port", guest: 8080, host: 9999
  config.vm.network :public_network,
                        :dev => "#{$default_network_router}",
                        :mode => "bridge"
                        # :type => "bridge"
  config.vm.provision "file", source: "ssh.qe.tar", destination: "/tmp/ssh.qe.tar"
  #kagent-jenkins will contain jenkins-cli.jar
  config.vm.provision "file", source: "kagent-jenkins/", destination: "$HOME/kagent-jenkins"  
  config.vm.provision "shell", inline: $script

  config.vm.provider :libvirt do |v|
    v.memory = 18432
    v.cpus = 2
    v.nested = true
    # v.linked_clone = true
  end
end
